name: Deploy to ephemeral environment

on:
  pull_request: 
    types: [opened, synchronize]
    branches:
     - dev
     
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ci${{ github.event.pull_request.number }}

jobs:
  deploy:
    env:
      STAGE: ci${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run:  VITE_API_KEY=da2-eqqtdjea6jhhja6o5odpop6y5q VITE_API_HOST=https://zjtfzllrnvecnn3zkysgjfbhdm.appsync-api.us-east-1.amazonaws.com/graphql npx projen build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::042405425993:role/GitHubAdminAccess
          aws-region: us-east-1
      - name: Deploy
        working-directory: ./backend
        run: npx cdk deploy --all --verbose --require-approval never --concurrency 5
      - name: pwd1111111
        run: pwd
      - name: LiiIII
        run: ls -al
      - name: pwd222222
        working-directory: ./backend
        run: pwd
      - name: Lii22222
        working-directory: ./backend
        run: ls -al
      - name: pwd3333
        working-directory: ./backend/cdk.out
        run: pwd
      - name: Lii33333
        working-directory: ./backend/cdk.out
        run: ls -al
      - name: Comment PR
        uses: actions/github-script@v7
        id: plan-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComments = comments.filter(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Deployed to')
            });
            // 2. Delete previous comments so PR timeline makes sense
            botComments.forEach(botComment => {
                github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            });
            // 3. Create new comment
            const fs = require('fs')
            const path = require('path')
            const jsonString = fs.readFileSync(path.resolve('backend/cdk.out/resources.json'))
            const output = `Deployed to ${{env.APP_NAME}}
            <details><summary>View stack outputs</summary>

            \`\`\`json
            ${jsonString}
            \`\`\`

            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
