name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write



concurrency:
  group: ci${{ github.event.pull_request.number }}

jobs:
  deploy:
    env:
      group: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx projen build
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::042405425993:role/GitHubAdminAccess
          aws-region: us-east-1
      - name: Deploy
        working-directory: ./backend
        run: STAGE=${{ env.GITHUB_REF_SLUG }} npx cdk deploy --all --verbose --require-approval never